Add Dockerfile for rangda
openware/rangda pull request #6
Opened 2018-09-29 15:13 UTC by alinetskyi

2018-10-02 15:46 UTC, kovetskiy requested changes

2018-10-02 15:46 UTC, kovetskiy commented on cmd/rangda/db_controller.go
> +	Pwd     string `env:"DATABASE_PASSWORD" default:""`
Pwd -> Password

2018-10-02 15:46 UTC, kovetskiy commented on cmd/rangda/db_controller.go
> +	DB_name string `env:"DATABASE_NAME" default:"barong_development"`
Name

2018-10-02 15:46 UTC, kovetskiy commented on cmd/rangda/db_controller.go
> +func connect_to_db() bool {
such function should return pointer on *sql.DB and error, not bool

2018-10-02 15:46 UTC, kovetskiy commented on cmd/rangda/db_controller.go
> +		panic(err)
panic should be used only in emergency cases, missing config file or broken db connection is not emergency case. 

Emergency case it's when the program can't run anymore, for example, nil dereference is real case when you should panic.

2018-10-03 08:23 UTC, seletskiy commented
@alinetskyi: hey, make sure to read [common changes requested in Go code during PRs][1].

Relevant links to this PR are: [don't panic][2] and [use mixed caps][3].

[1]: https://github.com/golang/go/wiki/CodeReviewComments
[2]: https://github.com/golang/go/wiki/CodeReviewComments#dont-panic
[3]: https://github.com/golang/go/wiki/CodeReviewComments#mixed-caps

2018-10-03 13:38 UTC, closed without merging